# Creates an embedding vector representing the input text.
# POST https://api.openai.com/v1/embeddings

# curl https://api.openai.com/v1/embeddings
#  -H "Authorization: Bearer $OPENAI_API_KEY"
#  -H "Content-Type: application/json"
#  -d '{
#    "input": "The food was delicious and the waiter...",
#    "model": "text-embedding-ada-002"
#  }'

POST https://api.openai.com/v1/embeddings
Authorization: Bearer {{OPENAI_API_KEY}}
Content-Type: application/json

{
  "input": "The food was delicious and the waiter...",
  "model": "text-embedding-ada-002"
}

###

